language: go

go:
  - "1.x"

services:
  - docker

install:
  - make docker
  - make docker-test

after_success:
  if [ "$TRAVIS_BRANCH" == "master" ]; then 
    make docker-login ;
    make docker-publish ;
  fi

