language: go

go:
  - "1.x"

services:
  - docker

install:
  - make deps-install
  - make
  - make docker
  - make docker-test

deploy:
  provider: script
  script:
  - make docker-login
  - make docker-publish
  on:
    branch: master
