version: "3.1"
services:
  proxy:
    image: internal/docker-sni-router
    build: .
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    environment:
      DOCKER_NETWORK: "public"
    networks:
    - public
    ports:
    - 443:443
    - 80:80
networks:
  public:
    external:
      name: public
